[build]
  command = "next build && next export"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/gold-rate.html"
  to = "/gold-rates"
  status = 200

[[redirects]]
  from = "/gold-rate/:state.html"
  to = "/states/:state"
  status = 200

[[redirects]]
  from = "/gold-rates/:city.html"
  to = "/cities/:city"
  status = 200
