// Static representative city mapping per state
// Ensure each mapped city exists in states_to_cities.json and has a data JSON
export const stateToRepresentativeCity: Record<string, string> = {
  'Andhra Pradesh': 'Vijayawada',
  'Arunachal Pradesh': 'Itanagar',
  'Assam': 'Guwahati',
  'Bihar': 'Patna',
  'Chhattisgarh': 'Raipur',
  'Goa': 'Panaji',
  'Gujarat': 'Ahmedabad',
  'Haryana': 'Gurgaon',
  'Himachal Pradesh': 'Shimla',
  'Jammu and Kashmir': 'Srinagar',
  'Jharkhand': 'Ranchi',
  'Karnataka': 'Bangalore',
  'Kerala': 'Kochi',
  'Madhya Pradesh': 'Bhopal',
  'Maharashtra': 'Mumbai',
  'Manipur': 'Imphal',
  'Meghalaya': 'Shillong',
  'Mizoram': 'Aizawl',
  'Nagaland': 'Kohima',
  'Odisha': 'Bhubaneswar',
  'Punjab': 'Ludhiana',
  'Rajasthan': 'Jaipur',
  'Sikkim': 'Gangtok',
  'Tamil Nadu': 'Chennai',
  'Telangana': 'Hyderabad',
  'Tripura': 'Agartala',
  'Uttar Pradesh': 'Lucknow',
  'Uttarakhand': 'Dehradun',
  'West Bengal': 'Kolkata',
  'Delhi': 'Delhi',
  'Chandigarh': 'Chandigarh',
  'Goa (UT)': 'Panaji',
  'Andaman and Nicobar Islands': 'Port Blair',
  'Dadra and Nagar Haveli and Daman and Diu': 'Daman',
  'Lakshadweep': 'Kavaratti',
  'Puducherry': 'Pondicherry',
};


